version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/jx_web_portals
    ports:
      - "80:8000"

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - "${MYSQL_DIR}/data:/var/lib/mysql"
      - "${MYSQL_DIR}/conf.d:/etc/mysql/conf.d"
    environment:
      # 环境变量
      - MYSQL_ROOT_PASSWORD=123456
